### ISSUE TITLE
Service Fails on Truncated JPG

### ISSUE THREAD

**Issue by malvidin** [CybercentreCanada/assemblyline-service-characterize#12]
The image in the attached archive fails (TASK PREEMPTED)

[truncated_shutterstock_498131416.zip](https://github.com/CybercentreCanada/assemblyline-service-characterize/files/6591883/truncated_shutterstock_498131416.zip)
Related to this issue:
https://github.com/CybercentreCanada/assemblyline-service-oletools/issues/20

**Comment by cccs-jh** [comment]
Thank you for reporting this, Oletools no longer extracts truncated files and an issue the hachoir library has with parsing truncated jpegs has been reported to that project.
